# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FillUP-Skeleton' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'GoogleSignIn'
  pod 'GoogleMaps'
  pod 'GooglePlaces'

  # Pods for FillUP-Skeleton

  target 'FillUP-SkeletonTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FillUP-SkeletonUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
